name: artic-ncov2019-illumina
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.6
  - biopython=1.79
  - libxcb
  - matplotlib=3.3.4
  - pandas=1.1.5
  - bwa=0.7.17=pl5.22.0_2
  - samtools=1.15
  - bcftools=1.15
  - trim-galore=0.6.5
  - ivar=1.3.1
  - pyvcf=0.6.8
  - pyyaml=5.3.1
  - openjdk=11.0.8
  - nextflow=21.10.6
  - pip:
    - click==7.1.2
