name: artic
channels:
  - epi2melabs
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - aplanat=0.5.4
  - biopython=1.78
  - matplotlib=3.6.2
  - pandas=1.2.4
  - samtools=1.12
  - libxcb
    #- cutadapt=3.1
    #- dnaio=0.4.4
  - fastcat=0.3.6
  - np-artic=1.3.0=py_11
  - pomoxis=0.3.6
  - setuptools=59.8.0
  - openjdk=11.0.8
  - nextflow=22.10.0
  - pip:
    - click==7.1.2
